import { Inter } from 'next/font/google'
import SideBar from './components/SideBar';
import Footer from './components/Footer';
import styles from '@/styles/globe.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
